### ISSUE TITLE
Urls for Hotel Packages invalid

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/isearch-ui#186] opened 2016-06-01 16:38 UTC
when attempting to click on a Package we are getting a 404 error ... (*.json file not found on S3*)
http://s3-eu-west-1.amazonaws.com/www.tcdl.io/isearch/0.15/index.html
![ui-hotel-url-invalid](https://cloud.githubusercontent.com/assets/194400/15717432/ede186e4-281e-11e6-8e16-c1577200a2c0.png)

the url for the package is defined at:
https://github.com/numo-labs/lambda-ne-classic-package-provider/blob/0c6c726f565ac7cb99da2aac03219a3240b7a216/index.js#L41

and is used as the `Key` for the S3 object in:
https://github.com/numo-labs/aws-lambda-helper/blob/0ff31a43ffe31df4cbdfcb8c7188f8817addc359/lib/index.js#L321

@Kumjami let me know if you need any help investigating.

**Comment by Kumjami** [comment] 2016-06-02 08:45
@nelsonic Currently, we are receiving the proper URL at front end, but while using it for routing https://github.com/numo-labs/isearch-ui/blob/master/src/components/search-results/index.js#L81 the last letter of the URL is being changed somehow. 
I'm researching regarding react-redux-router behavior to see if there is maybe a bug there. 
This is something quite "random". It's not happening always, but most of the times. And it's not happening with articles so far. So I guess the problem is at our side.

**Comment by Kumjami** [comment] 2016-06-02 12:26
Definitively it has nothing to do regarding front end. I was wrong. 

There is a delay at S3 while storing data. So we might have in the front end some data that have not being stored yet at S3.

**Comment by nelsonic** [comment] 2016-06-02 12:46
Oh... that *might* explain it.
However in our tests the latency to *save* the record (50ms) is less time than it takes to return the result to the client via WebSockets so it *should always* be saved/available by the time the user clicks on a package.
Should we only return the result to the client *after* we know it's been written to S3?

**Comment by Kumjami** [comment] 2016-06-02 12:52
I think yes, I have been trying it manually, trying to find packages at S3 inside amazon console. And I found that there were not here for a while. I had time to open dev tools, search for items at redux, check urls, check severals packages, and then I went to S3 and realize that there were no .json. After a while it was there, so... in some cases it could take quite long. 
I don't know if its a matter of usage (More requests, less writing speed), but might be the reason why this looks like "random". 

With articles I didn't have any problem, maybe due to there are less articles.

**Comment by nelsonic** [comment] 2016-06-02 14:51
@Kumjami the `lambda-ne-classic-package-provider` has been re-deployed with the latest version of `aws-lambda-helper` so records are written to S3 *before* they are published to the SNS topic. 
please confirm if that is/was the issue...

**Comment by nelsonic** [comment] 2016-06-03 11:22
@Kumjami please confirm this is working. 👍 
(*close the issue if everything is OK. thanks!*)

**Comment by Kumjami** [comment] 2016-06-14 15:20
Working! Closing it!

**Closed by Kumjami** 2016-06-14 15:20 UTC
Labels: bug, help wanted
