### ISSUE TITLE
Hotels with no rating

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#391] opened 2016-07-14 12:59 UTC
To ensure a full fix for the issue being opened can you please provide:

- Tags Searched: Spanien
- Page URL: http://inspirationalsearch.spies.dk/isearch/1.0.23/?search=city%20trip#/?_k=ceiiy2
- technical info

 Mobile Phone
 Android
 Chrome 51.0*
 360x568

### Screen Shot

![Screenshot](https://usabilla-feedback-live.s3.amazonaws.com/57873ca464ad106dd449749f/detail)

### Expected Behaviour
Each hotel has a rating.

### Actual Behaviour
Some hotels does not have any rating, or it looks as of they have a rating of 0

### Further Information
[usabilla issue](https://app.usabilla.com/feedback/item/203fbb466ebe3d32388584e8fc156f0cce2be7ac)

**Comment by tomgco** [comment] 2016-07-15 09:36
I can confirm that this is happening for me on `1.0.23` but not on `prod`.

I have a feeling that this might be due to the dynamic package provider.

**Comment by tomgco** [comment] 2016-07-15 09:47
By having a look at an affected tile `https://s3-eu-west-1.amazonaws.com/numo-search-results/ci/56748180-4a6f-11e6-b241-e79f82ac3332/183766.json` I can see that star rating is set to 0.

So this might be due to a lack of data from the actual API itself meaning we can't really do much about it, if this is the case.

**Comment by tomgco** [comment] 2016-07-15 09:53
Digging deeper it seems that all star ratings are based on the guest rating, which if some have not been reviewed, might be `0`. 

https://github.com/numo-labs/lambda-ne-classic-package-provider/blob/f07780db6c0fecf392f54799424e880afbd7141e/lib/result_mapper.js#L125

Maybe we can switch to the "doubledRating" field?

**Comment by emiledskar** [comment] 2016-07-18 07:56
Ah okey, so there is no field that correspond directly to the rating we are seeing on the spies.dk website? 
The [same hotel](http://www.spies.dk/spanien/barcelona/roger-de-lluria) at spies.dk is displaying a rating of 4 stars.

**Comment by tomgco** [comment] 2016-07-18 08:53
Once these: https://github.com/numo-labs/lambda-ne-classic-package-provider/pull/112 and https://github.com/numo-labs/lambda-ne-dynamic-package-provider/pull/4 get merged the issue should be resolved.

**Comment by lennym** [comment] 2016-07-18 09:12
> Once these: numo-labs/lambda-ne-classic-package-provider#112 and numo-labs/lambda-ne-dynamic-package-provider#4 get merged the issue should be resolved.

Both merged now

**Comment by tomgco** [comment] 2016-07-19 11:03
Should now be fixed, I am closing this issue.

**Closed by tomgco** 2016-07-19 11:03 UTC
Labels: bug, content
