### ISSUE TITLE
Inconsistent data: Top selection hotel has a zero rating...

### ISSUE THREAD

**Issue by jackcarlisle** [numo-labs/isearch-ui#355] opened 2016-07-04 13:06 UTC
<img width="404" alt="screen shot 2016-07-04 at 14 05 24" src="https://cloud.githubusercontent.com/assets/12450298/16561323/75a4e91e-41f0-11e6-8f1e-4b1d91e913f9.png">

**Comment by tomgco** [comment] 2016-07-04 14:07
Would you be able to provide the following:

- Tags searched:
- Logs ID: [(Open debug console)](https://github.com/numo-labs/isearch-ui#debugging-tracing-requests)
- Tracy ID: [(Open debug console)](https://github.com/numo-labs/isearch-ui#debugging-tracing-requests)

**Comment by tomgco** [comment] 2016-07-04 15:01
@jackcarlisle and I just looked into this together and it seems that the issue is no longer present...

I will close this for now as hopefully this was an upstream issue in the ne-classic provider.

**Closed by tomgco** 2016-07-04 15:01 UTC
Labels: help wanted, question

**Comment by jackcarlisle** [comment] 2016-07-04 15:04
👍
