### ISSUE TITLE
Strange tags are suggested in dropdown 

### ISSUE THREAD

**Issue by emiledskar** [numo-labs/isearch-ui#418] opened 2016-07-19 12:48 UTC
Tags Searched: n/a
Page URL: http://inspirationalsearch.spies.dk/isearch/prod/#/?_k=bp732o
Web Browser: http://whatsmybrowser.org/b/WBAJVLR

### Screen Shot

![image](https://cloud.githubusercontent.com/assets/8721221/16950230/860b23a6-4dbf-11e6-82d9-31e6e92767d9.png)

### Information
Searching for "h" returns two tags with the name "search".

**Comment by Kumjami** [comment] 2016-07-25 11:38
@emiledskar this is not a "begin with" match, its a "contain" do we want it to be "begin with"?
If not, just simply we would have to remove the "search" tag or mark it as `inactive`

**Comment by emiledskar** [comment] 2016-07-25 12:34
@Kumjami The contain match is working like it should. I'm more curious about the tag "Search" because I can't find that one in the taggable UI and also it is a weird tag to have.

**Comment by lennym** [comment] 2016-07-25 12:45
One of the `search` results is `geo:geonames.2911298` - Hamburg.

The other is `geo:geonames.1581130` - Hanoi

Both have their label property set to `search` in taggable-ui.

**Comment by Kumjami** [comment] 2016-07-25 12:45
@emiledskar maybe it's because the difference between label and value? is it possible that we have "search" as the value for any tag? (maybe I'm taking a wrong field to show, besides that having a "search tag or values makes no sense)

**Comment by tomgco** [comment] 2016-07-25 13:03
> One of the search results is geo:geonames.2911298 - Hamburg.
> 
> The other is geo:geonames.1581130 - Hanoi
> 
> Both have their label property set to search in taggable-ui.

Just confirmed what lenny mentioned. The content is tagged with this incorrectly. I will proceed to update this and remove the `search` labels.

**Comment by tomgco** [comment] 2016-07-25 13:24
This is now fixed.

**Closed by tomgco** 2016-07-25 13:24 UTC
Labels: bug, ci, content
